security:
  oauth2:
    resource:
      jwt:
        key-value: |
         -----BEGIN PUBLIC KEY-----
         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9GHOY7QOSNSILyrTv8Ox
         76iuZe7jXajTdM6l8EffKRdsSbSEv6LpUj43twcIiNa16/eHqoZSs0t8ZgpYWaNo
         Y3yt3Howpr3Ypo3k1A8BvY1Lsicf8mMzWlFJyLFWM6IPsqta69VT02UMMcRMWCap
         4k8adOAJkSngm5VmpmY+SxSgtAxuBF+etvofeFmTCF9hMKZX55uy2eKjHoM/pYww
         KnKsVr851whR/Qo6QkO8LoacCXBAgX4MxT84Ap9qsUpSnQIq7Agi9mYaQvUpbhnI
         MfE0Vi3WMiNUjWqle5YXsOXE2uyMXQ+q1wY4ZyHaiqaRMb3+WTM7TeB6NTcKZXmB
         +wIDAQAB
         -----END PUBLIC KEY-----           