spring:
  h2:
    console:
      enabled: true

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: customer
      client-secret: customer123